services:
  - type: web
    name: baserow
    env: docker
    repo: https://github.com/KumbuBot/baserow
    branch: main
    plan: free
    envVars:
      - key: BASEROW_PUBLIC_URL
        value: https://baserow.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: baserow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: baserow-redis
          type: redis
          property: connectionString

  - type: redis
    name: baserow-redis
    ipAllowList: []

  - type: postgres
    name: baserow-db
    plan: free
    ipAllowList: []
    user: baserow
    databaseName: baserow
